id: P003231
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 2021-12-17 10:49:03.244790
source_metadata:
  id: bdr:W1AC238
  title: བོན་གྱི་ཤེས་རིག་ཚིག་མཛོད།
  author: ''
  volumes:
    f76efb85e4634fb69a7b977930853ffc:
      image_group_id: I2PD18148
      title: ''
      volume_number: 1
      total_pages: 846
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
